package ipmitool

import (
	"testing"
)

func TestParsingSensorData(t *testing.T) {
	rawData := []reading{
		{Sensor: "SEL", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Intrusion", Reading: "0x0", Units: "discrete", Status: "0x0080"},
		{Sensor: "Fan1A", Reading: "6960.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan2A", Reading: "6960.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan3A", Reading: "7080.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan4A", Reading: "6840.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan5A", Reading: "6960.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan6A", Reading: "7080.000", Units: "RPM", Status: "ok"},
		{Sensor: "Inlet Temp", Reading: "21.000", Units: "degrees C", Status: "ok"},
		{Sensor: "CPU Usage", Reading: "7.000", Units: "percent", Status: "ok"},
		{Sensor: "IO Usage", Reading: "0.000", Units: "percent", Status: "ok"},
		{Sensor: "MEM Usage", Reading: "0.000", Units: "percent", Status: "ok"},
		{Sensor: "SYS Usage", Reading: "8.000", Units: "percent", Status: "ok"},
		{Sensor: "Exhaust Temp", Reading: "26.000", Units: "degrees C", Status: "ok"},
		{Sensor: "Temp", Reading: "37.000", Units: "degrees C", Status: "ok"},
		{Sensor: "Temp", Reading: "34.000", Units: "degrees C", Status: "ok"},
		{Sensor: "OS Watchdog", Reading: "0x0", Units: "discrete", Status: "0x0080"},
		{Sensor: "VCORE PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "VCORE PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "3.3V PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "5V AUX PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "USB Cable Pres", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "VGA Cable Pres", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Dedicated NIC", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M23 VPP PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M23 VPP PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "2.5V AUX PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "1.05V PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M23 VDDQ PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M23 VTT PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "5V SWITCH PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "DIMM PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "VCCIO PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M01 VDDQ PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M01 VDDQ PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M23 VTT PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M01 VTT PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "NDC PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "LCD Cable Pres", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M01 VPP PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M01 VPP PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M23 VDDQ PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presences", Reading: "0x0", Units: "discrete", Status: "0x0280"},
		{Sensor: "Status", Reading: "0x0", Units: "discrete", Status: "0x8080"},
		{Sensor: "Status", Reading: "0x0", Units: "discrete", Status: "0x8080"},
		{Sensor: "Fan Redundancy", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Riser Config Err", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Riser 3 Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "1.5V PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "1.5V AUX PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "FIVR PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "FIVR PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "PS2 PG Fail", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "PS1 PG Fail", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "BP0 5V PG", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "BP1 5V PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "BP2 5V PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "M01 VTT PG", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "PCIe Slot1", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCIe Slot2", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCIe Slot3", Reading: "0x0", Units: "discrete", Status: "0x0080"},
		{Sensor: "PCIe Slot4", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCIe Slot5", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCIe Slot6", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCIe Slot7", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "vFlash", Reading: "0x0", Units: "discrete", Status: "0x0080"},
		{Sensor: "CMOS Battery", Reading: "0x0", Units: "discrete", Status: "0x0080"},
		{Sensor: "ROMB Battery", Reading: "0x0", Units: "discrete", Status: "0x0080"},
		{Sensor: "ROMB Battery", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "BP1 Presence", Reading: "0x0", Units: "discrete", Status: "0x0280"},
		{Sensor: "BP2 Presence", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Fan7A", Reading: "6960.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan1B", Reading: "6480.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan2B", Reading: "6600.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan3B", Reading: "6480.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan4B", Reading: "6360.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan5B", Reading: "6600.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan6B", Reading: "6480.000", Units: "RPM", Status: "ok"},
		{Sensor: "Fan7B", Reading: "6600.000", Units: "RPM", Status: "ok"},
		{Sensor: "Current 1", Reading: "0.800", Units: "Amps", Status: "ok"},
		{Sensor: "Current 2", Reading: "0.000", Units: "Amps", Status: "ok"},
		{Sensor: "Voltage 1", Reading: "120.000", Units: "Volts", Status: "ok"},
		{Sensor: "Voltage 2", Reading: "120.000", Units: "Volts", Status: "ok"},
		{Sensor: "PS Redundancy", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Status", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Status", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Pwr Consumption", Reading: "112.000", Units: "Watts", Status: "ok"},
		{Sensor: "Power Optimized", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "SD1", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "SD2", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Redundancy", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "ECC Corr Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "ECC Uncorr Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "I/O Channel Chk", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCI Parity Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCI System Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "SBE Log Disabled", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Logging Disabled", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Unknown", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "CPU Protocol Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "CPU Bus PERR", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "CPU Init Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "CPU Machine Chk", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Memory Spared", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Memory Mirrored", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Memory RAID", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Memory Added", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Memory Removed", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Memory Cfg Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Mem Redun Gain", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "PCIE Fatal Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Additional Info", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Mem ECC Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Mem CRC Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "USB Over-current", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "POST Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Mem Overtemp", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "iDPT Memfail", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Mem Fatal SB CRC", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Mem Fatal NB CRC", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "OS Watchdog Time", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Non Fatal PCI Er", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Interconnect Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "CPU TDP", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "CPUMachineCheck", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "NonFatalSSDError", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "NonFatalPCIExpEr", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Fatal IO Error", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Interconnect Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Link Error", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "FatalPCIExpEr", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "MRC Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "MRC Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "MSR Info Log", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "TXT Status", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Drive 0", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Drive 15", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable SAS A0", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Cable PCIe B", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable PCIe C", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable PCIe D", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable PCIe A", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable SAS B0", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Cable SAS A1", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable SAS B1", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable SAS A2", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Cable SAS B2", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Power Cable", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Signal Cable", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Power Cable", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "Signal Cable", Reading: "0x0", Units: "discrete", Status: "0x0180"},
		{Sensor: "PFault Fail Safe", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "A", Reading: "0x0", Units: "discrete", Status: "0x4080"},
		{Sensor: "Link Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "NonFatalPCIErBus", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Link Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Chipset Err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Err Reg Pointer", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "QPIRC Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "QPIRC Warning", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Hdwr version err", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Chassis Mismatch", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "B", Reading: "0x0", Units: "discrete", Status: "0x4080"},
		{Sensor: "FatalPCIErrOnBus", Reading: "na", Units: "discrete", Status: "na"},
		{Sensor: "Fatal PCI SSD Er", Reading: "na", Units: "discrete", Status: "na"},
	}

	sensors, err := parseSensorData(rawData)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !sensors.ExhaustOk {
		t.Error("sensors.ExhaustOk should have been true")
	}
	if !sensors.TempOk {
		t.Error("sensors.TempOk should have been true")
	}
	if !sensors.PowerConsumptionOk {
		t.Error("sensors.PowerConsumptionOk should have been true")
	}
	if sensors.PowerConsumptionWatts != 112 {
		t.Errorf("sensors.PowerConsumptionWatts should have been 112, got %f", sensors.PowerConsumptionWatts)
	}
	if sensors.AvgFanSpeedRPM == 0 {
		t.Error("sensors.AvgFanSpeedRPM should not have been empty")
	}
	if sensors.MaxTempCelsius != 37 {
		t.Errorf("sensors.MaxTempCelsius should have been 37, got %f", sensors.MaxTempCelsius)
	}
}
